export const SET_JWT_TOKEN = "SET_JWT_TOKEN"
export const SET_USERNAME = "SET_USERNAME"
export const SET_LOGINED = 'SET_LOGINED'
export const SET_DATAARR = 'SET_DATAARR'
export const SPLICE_DATAARR = 'SPLICE_DATAARR'
export const SET_UPDATEINDEX = 'SET_UPDATEINDEX'
export const SET_UPDATE_OBJ = 'SET_UPDATE_OBJ'
export const SET_STEP_OBJ = 'SET_STEP_OBJ'
